server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: reservation
          uri: http://localhost:8081
          predicates:
            - Path=/reservations/**,/reservationinquiries/**
        - id: Reservationmanagement
          uri: http://localhost:8082
          predicates:
            - Path=/hotelReservationManagements/**
        - id: payment
          uri: http://localhost:8083
          predicates:
            - Path=/payments/**
        - id: CustomerManagement
          uri: http://localhost:8084
          predicates:
            - Path=/customerManagements/**,/customerReservationInfoes/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: reservation
          uri: http://reservation:8080
          predicates:
            - Path=/reservations/**,/reservationinquiries/**
        - id: Reservationmanagement
          uri: http://reservationmanagement:8080
          predicates:
            - Path=/hotelReservationManagements/**
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/payments/**
        - id: CustomerManagement
          uri: http://skccuser24-customermanagement:8080
          predicates:
            - Path=/customerManagements/**,/customerReservationInfoes/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
